apiVersion: v1
kind: Service
metadata:
  name: chess-club-ranking-system-service
spec:
  type: NodePort
  selector:
    app: chess-club-ranking-system
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5000
      nodePort: 30080
